import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { useRouter } from "next/router";
import Logo from '../components/logo'
import Loader from '../components/loading'
// How to build an Animated Button with React Aria and Framer Motion 
const Home: NextPage = () => {
  const [ctrlLeft, setctrlLeft] = useState(true);
  const [ctrlRight, setctrlRight] = useState(true);
  const router = useRouter();
  setTimeout(() => {
    setctrlLeft(false);
  }, 4000);
  async function pagehandler(e :any) {
      // let [res] = await Promise.allSettled({
      //     // action
      //    new Promise((resolve) => setTimeout(resolve, 8000)),
      // });
      // let json = res.value;
      await new Promise((resolve) => setTimeout(resolve, 800))
      e.preventDefault()
      return router.push(`/next`)
  }
  return (
    <div className="bg-[#1f1f1f] h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <header>
          <motion.h1
            className="mx-96 flex justify-center items-center pt-5  "
            whileHover={{
              scale: 1.5,
              textShadow: "0px 0px 8px rgb(255,255,255) ",
            }}
            transition={{
              mass: 0.4,
              damping: 8,
              when: "beforeChildren",
              staggerChildren: 2,
              type: "spring",
            }}
            initial={{ y: -50 }}
            animate={{ y: 0 }}
          >
            Motion
            <motion.p
              animate={{ scale: [1.5, 2.5, 1.5, 2.5, 1.5] }}
              whileHover={{
                scale: [1.5, 2.5, 1.5, 2.5, 1.5, 2.5, 1.5],
              }}
              transition={{
                duration: 1,
              }}
            >
              💚
            </motion.p>
          </motion.h1>
          <motion.div className="ml-[10%] " >
          <Logo />
          <Loader />
          </motion.div>
        </header>
        <div>
          <AnimatePresence>
            {ctrlLeft && (
              <motion.h1
                transition={{
                  delay: 0.5,
                  duration: 1,
                  type: "spring",
                  stiffness: 200,
                }}
                initial={{ opacity: 0, x: -300 }}
                animate={{ opacity: 1, x: 10 }}
                exit={{ y: "100vh" }}
                className="z-[50] pt-60 fixed right-[60%] text-red-800 font-bold text-[45px] "
              >
                freedem{" "}
              </motion.h1>
            )}
          </AnimatePresence>
          <div className="flex">
            <div className="z-[5] w-full h-full items-center justify-center flex pt-5">
              <AnimatePresence exitBeforeEnter>
                <motion.img
                  key={router.route}
                  exit={{ opacity: 0, x: "100vw", y: "-100vw" }}
                  transition={{ delay: 0, duration: 1 }}
                  initial={{ opacity: 0, x: "-100vw", y: "100vw" }}
                  animate={{ opacity: 1, x: 0, y: 0 }}
                  src="/19.png"
                  alt=""
                />
              </AnimatePresence>
            </div>
            <motion.h1
              transition={{ delay: 1, duration: 1, type: "tween" }}
              initial={{ opacity: 0, x: 300 }}
              animate={{ opacity: 1, x: 10 }}
              className="z-[50] pt-80 fixed left-[60%]  text-red-800 font-bold text-[40px]"
            >
              near
            </motion.h1>
          </div>
        </div>
        <div className="flex justify-around top-0">
          <motion.button
            className="text-red-700"
            transition={{ delay: 0.5, duration: 1 }}
            initial={{ opacity: 0, x: -300 }}
            animate={{ opacity: 1, x: 10 }}
            onClick={() => setctrlLeft(!ctrlLeft)}
          >
            ctrl left
          </motion.button>
            <motion.div
              transition={{ type: "spring", stiffness: 500 }}
              initial={{ opacity: 0, y: 10 }}
              onClick={pagehandler}
              animate={{ opacity: 1, y: 0 }}
              whileHover={{
                scale: 1.2,
                textShadow: "0px 0px 8px rgb(255,255,255)",
                boxShadow: "0px 0px 8px rgb(255,255,255)",
              }}
              className=" touch-none select-none cursor-pointer rounded-lg px-5 py-3 border border-red-800 hover:bg-red-800 hover:text-black hover:border-white transition-all duration-100"
            >
              start
            </motion.div>
          <motion.button
            transition={{ delay: 1, duration: 1, type: "tween" }}
            initial={{ opacity: 0, x: 300 }}
            animate={{ opacity: 1, x: 10 }}
            className="text-red-700"
          >
            ctrl right
          </motion.button>
        </div>
      </main>
    </div>
  );
};

export default Home;
